---
- name: Configure admin access
  hosts: all
  become: true
  roles:
    - role: ssh_user
      vars:
        ssh_user_name: "{{ lookup('env', 'USER') }}"
        ssh_user_pubkey_path: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
        ssh_user_sudo_commands: ALL
        ssh_user_sudo_nopasswd: false
        ssh_user_root_authorized: true
